export const TYPES = {
  INITIALIZE_STATE: "INITIALIZE_STATE",
  ADD_TO_CART: "ADD_TO_CART",
  ADD_ONE_FROM_CART: "ADD_ONE_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEMS",
  REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS",
  CLEAR_CART: "CLEAR_CART",
};
