export const TYPES = {
  INITIALIZE_PRODUCTS: "INITIALIZE_PRODUCTS",
  INITIALIZE_CART: "INITIALIZE_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM: "REMOVE_ITEMS",
  REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS",
  CLEAR_CART: "CLEAR_CART",
};
