import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./Components/Header";
import Footer from "./Components/Footer";
import CartProvider from "./Contexts/CartContext";
import UserProvider from "./Contexts/UserContext";
import SearchBar from "./Components/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Generic Ecommerce Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{!metadata.title}</title>
        <meta name="description" content={metadata.description!} />
      </head>
      <body className={inter.className}>
        <CartProvider>
          <UserProvider>
            <Header />
            {children}
            <SearchBar />
            <Footer />
          </UserProvider>
        </CartProvider>
      </body>
    </html>
  );
}
